# Generated by Django 5.2.5 on 2025-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('residenza', models.TextField(blank=True, null=True)),
                ('esperienza_finanziaria', models.TextField(blank=True, null=True)),
                ('visure', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
