# Generated by Django 5.2.5 on 2025-08-26 09:25

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_profiloutente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stato',
            field=models.CharField(choices=[('active', 'Attivo'), ('inactive', 'Non Attivo'), ('legal', 'Legale')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='pratiche',
            name='aggiornata_il',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pratiche',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pratiche',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pratiche',
            name='titolo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.models.client_directory_path)),
                ('descrizione', models.CharField(blank=True, max_length=255, null=True)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='crm.cliente')),
            ],
        ),
    ]
