# Generated by Django 5.2.5 on 2025-08-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_stato_pratiche_aggiornata_il_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore_nome', models.CharField(max_length=100)),
                ('testo', models.TextField()),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='crm.cliente')),
            ],
        ),
    ]
