# Generated by Django 5.2.5 on 2025-08-28 13:45

import crm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('anagrafici', 'Documenti anagrafici'),
                    ('pratiche', 'Pratiche'),
                    ('legali', 'Atti legali'),
                ],
                default='anagrafici',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='file',
            field=models.FileField(
                upload_to=crm.models.client_directory_path,
                validators=[django.core.validators.FileExtensionValidator(
                    allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']
                )]
            ),
        ),
    ]
