# Generated by Django 5.2.5 on 2025-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_documentocliente_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stato', models.CharField(choices=[('in_corso', 'In corso'), ('negativo', 'Esito negativo')], default='in_corso', max_length=20)),
                ('appuntamento_previsto', models.DateTimeField(blank=True, null=True)),
                ('motivazione_negativa', models.TextField(blank=True, null=True)),
                ('note_operatori', models.TextField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
