# Generated by Django 5.2.5 on 2025-09-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convertito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='convertito_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='da_lead', to='crm.cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='convertito_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_convertiti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='convertito_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archiviato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stato',
            field=models.CharField(choices=[('in_corso', 'In corso'), ('negativo', 'Esito negativo'), ('positivo', 'Esito positivo')], default='in_corso', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stato'], name='crm_lead_stato_7ab182_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['convertito', 'is_archiviato'], name='crm_lead_convert_1b3761_idx'),
        ),
    ]
