# Generated by Django 5.2.5 on 2025-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_convertito_lead_convertito_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consulenza_effettuata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='in_acquisizione',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='messaggio_inviato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='no_risposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='richiamare_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
