# Generated by Django 5.2.6 on 2025-10-14 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_consulenza_effettuata_lead_in_acquisizione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='primo_contatto',
            field=models.DateTimeField(blank=True, help_text='Data/ora del primo contatto', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='provenienza',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google'), ('passaparola', 'Passaparola')], default='', help_text='Da quale canale/social proviene il lead', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='consulente',
            field=models.ForeignKey(blank=True, help_text='Chi farà la consulenza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.consulente'),
        ),
    ]
