# Generated by Django 5.2.6 on 2025-10-14 02:03

from django.db import migrations


def seed_consulenti(apps, schema_editor):
    Consulente = apps.get_model("crm", "Consulente")
    Consulente.objects.get_or_create(nome="Yuri Bonato", defaults={"is_active": True})
    Consulente.objects.get_or_create(nome="Vincenzo Bonato", defaults={"is_active": True})
    
class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_consulente_lead_primo_contatto_lead_provenienza_and_more'),
    ]

    operations = [
    ]
