# Generated by Django 5.2.6 on 2025-10-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_seed_consulenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(choices=[('anagrafici', 'Documenti anagrafici'), ('pratiche', 'Pratiche'), ('legali', 'Atti legali'), ('visure', 'Visure')], default='anagrafici', max_length=20),
        ),
    ]
