# Generated by Django 5.2.6 on 2025-10-15 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_documentocliente_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('doc_visure', 'Documento in Visure'), ('doc_generico', 'Documento')], default='doc_generico', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letto', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche_generate', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche', to='crm.cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
