# Generated by Django 5.2.6 on 2025-10-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_notifica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifica',
            options={},
        ),
        migrations.RenameField(
            model_name='notifica',
            old_name='letto',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='notifica',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche', to='crm.documentocliente'),
        ),
        migrations.AddField(
            model_name='notifica',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='testo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('documento', 'Documento'), ('generica', 'Generica')], default='generica', max_length=20),
        ),
    ]
