# Generated by Django 5.2.6 on 2025-10-15 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_notifica_options_rename_letto_notifica_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documenti_inviati',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='istanza_visibilita',
            field=models.BooleanField(default=False, verbose_name='Istanza di visibilità'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='perizia_inviata',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SchedaConsulenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obiettivo', models.CharField(blank=True, max_length=255)),
                ('occupazione', models.CharField(blank=True, max_length=120)),
                ('reddito_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spese_mensili', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('esposizione_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ha_cqs', models.BooleanField(default=False)),
                ('ha_equitalia', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schede_consulenza', to='crm.cliente')),
                ('compilata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schede_consulenza_compilate', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schede_consulenza', to='crm.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
