# Generated by Django 5.2.6 on 2025-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_cliente_documenti_inviati_cliente_istanza_visibilita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='stato',
            field=models.CharField(choices=[('active', 'Attivo'), ('inactive', 'Non Attivo'), ('legal', 'Legale'), ('istanza', ' Istanza di visibilità')], default='active', max_length=10),
        ),
    ]
