# Generated by Django 5.2.7 on 2025-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_schedaconsulenza_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedaconsulenza',
            name='reddito_mensile',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='schedaconsulenza',
            name='spese_mensili',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
