# Generated by Django 5.2.7 on 2025-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_schedaconsulenza_reddito_mensile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedaconsulenza',
            name='reddito_mensile',
        ),
        migrations.RemoveField(
            model_name='schedaconsulenza',
            name='spese_mensili',
        ),
        migrations.AddField(
            model_name='schedaconsulenza',
            name='esposizione_finanziaria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedaconsulenza',
            name='esposizione_patrimoniale',
            field=models.TextField(blank=True),
        ),
    ]
