# Generated by Django 5.2.7 on 2025-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_remove_schedaconsulenza_reddito_mensile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(choices=[('anagrafici', 'Documenti anagrafici'), ('contratti', 'Contratti'), ('visure', 'Visure'), ('riscontro_istanza', 'Riscontro istanza'), ('proposta_transattiva', 'Proposta transattiva'), ('decreto_ingiuntivo', 'Decreto ingiuntivo'), ('precetto', 'Precetto'), ('pignoramento', 'Pignoramento'), ('mandato', 'Mandato'), ('pratiche', 'LEGACY – Pratiche'), ('legali', 'LEGACY – Atti legali')], db_index=True, default='anagrafici', max_length=32),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['cliente', 'categoria'], name='crm_documen_cliente_52fe7a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['cliente', 'caricato_il'], name='crm_documen_cliente_1d471c_idx'),
        ),
    ]
