# Generated by Django 5.2.7 on 2025-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_documentocliente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocliente',
            options={'ordering': ('-caricato_il',)},
        ),
        migrations.RemoveField(
            model_name='nota',
            name='autore_nome',
        ),
        migrations.AddField(
            model_name='nota',
            name='autore',
            field=models.CharField(blank=True, db_column='autore_nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='stato',
            field=models.CharField(choices=[('active', 'Attivo'), ('inactive', 'Non Attivo'), ('legal', 'Legale'), ('istanza', 'Istanza di visibilità')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stato',
            field=models.CharField(choices=[('in_corso', 'In corso'), ('negativo', 'Esito negativo'), ('positivo', 'Esito positivo')], db_index=True, default='in_corso', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='ruolo',
            field=models.CharField(choices=[('admin', 'Admin'), ('operatore', 'Operatore'), ('legale', 'Legale')], default='operatore', max_length=20),
        ),
    ]
