# Generated by Django 5.2.7 on 2025-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_documentocliente_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(choices=[('anagrafici', 'Documenti anagrafici'), ('scheda_consulenza', 'Scheda Consulenza'), ('contratti', 'Stragiudiziario'), ('visure', 'Visure'), ('riscontro_istanza', 'Riscontro istanza'), ('proposta_transattiva', 'Proposta transattiva'), ('decreto_ingiuntivo', 'Decreto ingiuntivo'), ('precetto', 'Precetto'), ('pignoramento', 'Pignoramento'), ('mandato', 'Mandato'), ('opposizione', 'Opposizione'), ('preventivi', 'Preventivi'), ('altro', 'Altro'), ('pratiche', 'LEGACY – Pratiche'), ('legali', 'LEGACY – Atti legali')], db_index=True, default='anagrafici', max_length=32),
        ),
    ]
