# Generated by Django 5.2.7 on 2025-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_documentocliente_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='stato',
            field=models.CharField(choices=[('active', 'Attivo'), ('inactive', 'Non Attivo'), ('legal', 'Legale'), ('istanza', 'Istanza di visibilità'), ('stragiudiziale', 'Stragiudiziale')], db_index=True, default='active', max_length=50),
        ),
    ]
