# Generated by Django 5.2.7 on 2025-11-24 23:40

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_documentocliente_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='file',
            field=models.FileField(upload_to=crm.models.client_directory_path),
        ),
    ]
