# Generated by Django 5.2.7 on 2026-02-24 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_documentocliente_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stato_operativo',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('msg_inviato', 'Messaggio inviato'), ('no_risposta', 'Senza risposta'), ('consulenza_eff', 'Consulenza effettuata'), ('in_acquisizione', 'In acquisizione'), ('non_competenza', 'Attività non di competenza'), ('attesa_contatti', 'Attesa contatti cliente')], db_index=True, default='nuovo', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(choices=[('anagrafici', 'Documenti anagrafici'), ('scheda_consulenza', 'Scheda Consulenza'), ('contratti', 'Privato Admin'), ('visure', 'Visure'), ('riscontro_istanza', 'Riscontro Istanza'), ('proposta_transattiva', 'Proposta transattiva'), ('decreto_ingiuntivo', 'Decreto ingiuntivo'), ('precetto', 'Precetto'), ('pignoramento', 'Pignoramento'), ('mandato', 'Mandato'), ('opposizione', 'Opposizione'), ('preventivi', 'Preventivi'), ('altro', 'Altro'), ('provvedimento', 'Provvedimenti'), ('richiesta_istanza', 'Richiesta Istanza'), ('reclamo', 'Reclamo'), ('pratiche', 'LEGACY – Pratiche'), ('legali', 'LEGACY – Atti legali')], db_index=True, default='anagrafici', max_length=32),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stato_operativo'], name='crm_lead_stato_o_4fd966_idx'),
        ),
    ]
