# Generated by Django 5.2.7 on 2026-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_lead_stato_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creditore_legale',
            field=models.CharField(blank=True, choices=[('banca_ifis', 'Banca Ifis'), ('mb_credit', 'MB Credit'), ('kruk', 'Kruk'), ('itacapital', 'Itacapital'), ('cherry_bank', 'Cherry Bank'), ('marathon_spv', 'Marathon SPV'), ('prelios', 'Prelios'), ('kerdos', 'Kerdos'), ('intrum', 'Intrum'), ('altro', 'Altro')], default='', help_text='Creditore/Banca/Finanziaria', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creditore_legale_altro',
            field=models.CharField(blank=True, help_text="Se selezioni 'Altro', scrivi qui il nome", max_length=120, null=True),
        ),
    ]
