# Generated by Django 5.2.7 on 2026-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_lead_ricontatti_stato_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stato_operativo',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('no_risposta', 'Senza risposta'), ('segreteria', 'Segreteria'), ('ha_staccato_lui', 'Ha staccato lui'), ('consulenza_eff', 'Consulenza effettuata'), ('non_competenza', 'Attività non di competenza'), ('attesa_contatti', 'Attesa contatti cliente'), ('non_contattare', 'Non contattare'), ('numero_errato', 'Numero errato'), ('blocco_chiamate', 'Blocco chiamate'), ('cliente_non_interessato', 'Cliente non interessato')], db_index=True, default='nuovo', max_length=30),
        ),
    ]
