# Generated by Django 5.2.7 on 2026-03-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migra_note_operatori_in_notalead(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    NotaLead = apps.get_model("crm", "NotaLead")
    ids_migrati = []
    for lead in Lead.objects.exclude(note_operatori__isnull=True).exclude(note_operatori=""):
        t = (lead.note_operatori or "").strip()
        if t:
            NotaLead.objects.create(lead_id=lead.pk, testo=t, autore_id=None)
            ids_migrati.append(lead.pk)
    if ids_migrati:
        Lead.objects.filter(pk__in=ids_migrati).update(note_operatori=None)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_alter_lead_stato_operativo_non_fascia_oraria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_lead_scritte', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='crm.lead')),
            ],
            options={
                'ordering': ('-creato_il',),
                'indexes': [models.Index(fields=['lead', '-creato_il'], name='crm_notalea_lead_id_bba287_idx')],
            },
        ),
        migrations.RunPython(migra_note_operatori_in_notalead, migrations.RunPython.noop),
    ]
